# Generated by Django 6.1 on 2026-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('course_class', models.CharField(max_length=150)),
                ('school_college', models.CharField(max_length=200)),
                ('university_board', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
